import type { Scenario, ScenarioComplexity, ScenarioSection } from "@/types";
import type { SnippetId } from "@/data/code-snippets";

const unorderedScenarios: Scenario[] = [
  {
    id: "simple-payment",
    title: "Marketplace Checkout",
    description:
      "Buyer creates a BOLT-11 invoice for a product listing. Platform routes the payment to the seller's wallet.",
    education:
      "In a Lightning marketplace, the checkout flow works like a simple invoice payment. The buyer requests an invoice for a product, and the platform handles routing. Lightning invoices can be shared as text or QR code and are single-use.",
    complexity: "simplest",
    requiredWallets: ["alice", "bob"],
    icon: "💸",
    snippetIds: ["make-invoice", "pay-invoice"] satisfies SnippetId[],
    prompts: [
      {
        title: "Pay-to-Continue Minesweeper",
        description:
          "Build a minesweeper game where hitting a mine lets you pay sats to resume instead of restarting.",
        prompt: `Build a minesweeper game where the player can pay a Lightning invoice to continue after hitting a mine.

Requirements:
- A playable minesweeper grid (e.g. 10x10 with 15 mines)
- Standard minesweeper rules: reveal tiles, flag mines, number hints
- When the player hits a mine, show a "Game Over" overlay with two options:
  - "Restart" (free, resets the board)
  - "Continue" (costs sats, removes the mine and lets the player keep playing)
- "Continue" generates a Lightning invoice, displays it as a QR code
- After payment is confirmed, dismiss the overlay and let the player resume
- Each continue costs more than the last (e.g. 10, 25, 50, 100 sats)
- Show a scoreboard with total sats spent and tiles cleared
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Play → hit mine → pay invoice to continue or restart for free.`,
      },
    ],
  },
  {
    id: "lookup-invoice",
    title: "Order Status Tracking",
    description:
      "Seller creates an invoice for an order. The platform or buyer can check if the order has been paid at any time.",
    education:
      "With NWC, sellers can look up the status of invoices generated by their wallet at any time. This is essential for marketplace order management — confirming whether a payment has been received before shipping.",
    complexity: "simple",
    requiredWallets: ["alice", "bob"],
    icon: "🔎",
    snippetIds: [
      "make-invoice",
      "lookup-invoice",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Point of Sale Terminal",
        description:
          "Build a simple point-of-sale terminal that creates invoices and confirms payment in real time.",
        prompt: `Build a point-of-sale (PoS) terminal that accepts Lightning payments.

Requirements:
- A keypad or input to enter the charge amount in sats
- An optional description field for the item or order
- A "Charge" button that creates an invoice and displays it as a large QR code
- Poll the invoice status and show a clear "Pending..." indicator while waiting
- When paid, show a success screen with a checkmark and the amount received
- A "New Sale" button to reset and start the next transaction
- Keep a list of completed sales for the current session
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Enter amount → charge → show QR → poll status → payment confirmed → ready for next sale.`,
      },
    ],
  },
  {
    id: "lnurl-verify",
    title: "Payment Verification",
    description:
      "Buyer requests an invoice from a seller's Lightning Address. The buyer can verify their payment went through.",
    education:
      "LNURL-Verify allows marketplace buyers to check the status of a payment at any time without accessing the seller's wallet. This is useful for order confirmation screens where the buyer needs real-time verification.",
    complexity: "medium",
    requiredWallets: ["alice", "bob"],
    icon: "🔎",
    snippetIds: [
      "request-invoice-from-address",
      "pay-invoice",
      "lnurl-verify",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Tip Jar / Donation Page",
        description:
          "Build a public donation page that verifies tips were received using LNURL-verify.",
        prompt: `Build a tip jar page where users send tips to a Lightning Address and the app verifies payment using LNURL-verify.

Requirements:
- Display a creator profile (name, avatar placeholder, bio)
- Input field for tip amount in sats with preset buttons (100, 500, 1000, 5000 sats)
- Optional message field from the tipper
- Request an invoice from the creator's Lightning Address
- Display the invoice as a QR code for the tipper to pay
- Use the LNURL-verify URL returned with the invoice to poll for payment confirmation (no wallet access needed)
- Show a thank you screen when LNURL-verify confirms the payment
- Display a running list of verified tips
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.
- No backend is needed

The flow: Choose amount → request invoice from Lightning Address → show QR → verify payment via LNURL-verify → show confirmation.`,
      },
    ],
  },
  {
    id: "lightning-address",
    title: "Seller Payout",
    description:
      "Pay sellers to their Lightning Address. The system handles invoice creation automatically for instant payouts.",
    education:
      "Sellers share their Lightning Address (like an email for payments) to receive marketplace payouts. Lightning addresses can be shared as text or QR code. The marketplace platform uses them to send earnings instantly without manual invoice creation.",
    complexity: "simple",
    requiredWallets: ["alice", "bob"],
    icon: "🔌",
    snippetIds: [
      "fetch-lightning-address",
      "request-invoice-from-address",
      "pay-lightning-address",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Rewards App",
        description:
          "Build an app where users register their Lightning Address and earn sats for completing actions.",
        prompt: `Build a rewards app that pays users to their Lightning Address when they complete actions.

Requirements:
- A registration form where users enter their name and Lightning Address
- A list of available tasks/actions (e.g. "Complete survey", "Refer a friend", "Watch a video")
- Each action has a reward amount in sats
- When a user completes an action, pay out the reward to their Lightning Address
- Show a confirmation with the payment details after each payout
- Display a leaderboard of users and their total earnings
- Store user profiles and completed actions in local state
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Register Lightning Address → complete an action → receive sats payout → see earnings on leaderboard.`,
      },
      {
        title: "Live Stream Donation Meter",
        description:
          "Build a live streaming platform where viewers stream sats to creators as they watch.",
        prompt: `Build a live streaming donation meter where viewers continuously stream sats to the creator while watching.

Requirements:
- A video player mockup (use a placeholder or video element)
- Creator profile with Lightning Address and suggested streaming rate (e.g. 20 sats/minute)
- When the viewer starts watching:
  - Begin streaming micro-payments to the creator's Lightning Address at regular intervals
  - Display a prominent streaming meter showing sats/minute being sent
  - Show a live counter of total sats streamed in this session
- Allow viewers to adjust their stream rate with a slider (1-100 sats/minute)
- Include a "Boost" button for sending a one-time larger payment (e.g. 1000 sats)
- Display a live activity feed of all streaming payments and boosts
- Show viewer stats: watch time, total streamed, average rate
- When the stream is paused or viewer leaves, stop the payment stream
- Include a leaderboard showing top supporters by total sats sent
- Display creator stats: total viewers streaming, total sats/minute incoming, session total
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Start watching → streaming begins automatically → adjust rate or boost → pause stops streaming → resume continues → see session totals.`,
      },
    ],
  },
  {
    id: "notifications",
    title: "Sale Alerts",
    description:
      "Subscribe to real-time payment notifications. Get alerted instantly when a product sells on your marketplace.",
    education:
      "NWC supports subscribing to payment notifications, allowing your marketplace to react instantly when sales come in. This enables real-time inventory updates, seller alerts, and order fulfillment triggers.",
    complexity: "medium",
    requiredWallets: ["alice", "bob"],
    icon: "🔔",
    snippetIds: [
      "subscribe-notifications",
      "request-invoice-from-address",
      "pay-lightning-address",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Streamer QR Donation Page",
        description:
          "Build a streamer overlay page that shows a QR code and plays alerts when payments arrive.",
        prompt: `Build a streamer donation page with real-time payment alerts.

Requirements:
- Display a large QR code for the streamer's Lightning Address or a static invoice
- Subscribe to payment notifications to react when payments arrive
- When a payment is received, show an animated alert overlay with the amount and sender message
- Play a sound effect on each new payment (use a simple beep or chime)
- Keep a live feed of recent donations scrolling on screen
- Show running total of donations received in the session
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Show QR → listener receives notification → animate alert → update donation feed.`,
      },
      {
        title: "Zap Lamp",
        description:
          "Build a virtual zap lamp that lights up and animates every time a Lightning payment is received.",
        prompt: `Build a virtual zap lamp that reacts to incoming Lightning payments with light animations.

Requirements:
- Display a large visual lamp or lightbulb in the center of the screen (use CSS/SVG, no images needed)
- The lamp starts in an "off" or dim state
- Subscribe to payment notifications on the connected wallet
- When a payment is received:
  - The lamp lights up with a bright glow animation
  - The color and intensity scale with the payment amount (e.g. small payments = warm yellow, large payments = bright white or electric blue)
  - Show the amount received as a floating label near the lamp
  - The glow fades out after a few seconds
- Display a payment counter and total sats received
- Show a live feed of recent payments below the lamp
- Include a "lamp status" indicator: idle, glowing, cooldown
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Connect wallet → subscribe to notifications → receive payment → lamp glows with amount-based intensity → fade back to idle.`,
      },
      {
        title: "Lightning Goats",
        description:
          "Build a fun app where goats get fed every time a Lightning payment is received — inspired by the real Lightning Goats project.",
        prompt: `Build a Lightning Goats app where incoming payments trigger a virtual goat feeding.

Requirements:
- Display a pasture scene with goat characters (use emoji 🐐 or simple CSS illustrations)
- Show a feeding trough that starts empty
- Subscribe to payment notifications on the connected wallet
- When a payment is received:
  - Animate food appearing in the trough (amount of food scales with sats received)
  - Goats walk over to the trough and start eating with a fun animation
  - Show a "+X sats" popup and a "Nom nom!" message
  - Play a goat bleat sound effect (optional, use a simple audio tone as fallback)
- Track feeding stats:
  - Total sats received
  - Number of feedings
  - "Goat happiness" meter that increases with more feedings
- Show a live log of recent feedings with timestamps and amounts
- Include a shareable Lightning Address or QR code so anyone can feed the goats
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Display goat pasture → subscribe to notifications → receive payment → animate goat feeding → update stats → wait for next payment.`,
      },
    ],
  },
  {
    id: "subscription-payments",
    title: "Recurring Orders",
    description:
      "Buyer sets up auto-replenishment for supplies on a regular interval using a budgeted wallet connection.",
    education:
      "Users can give budgeted wallet connections to a marketplace so it can charge them on a regular interval. This enables recurring product orders, auto-replenishment, and subscription box business models on Lightning.",
    howItWorks: [
      {
        title: "Connect",
        description:
          "Buyer provides the platform with their NWC connection, which has spending permissions.",
      },
      {
        title: "Configure",
        description:
          "Buyer sets the payment amount and interval for the recurring order.",
      },
      {
        title: "Charge",
        description:
          "Platform uses the buyer's connection to pay invoices to itself on a regular schedule.",
      },
    ],
    complexity: "medium",
    requiredWallets: ["alice", "bob"],
    icon: "🔄",
    snippetIds: [
      "subscribe-notifications",
      "request-invoice-from-address",
      "pay-lightning-address",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "SaaS Subscription Manager",
        description:
          "Build a subscription service that charges users on a recurring schedule via their wallet connection.",
        prompt: `Build a SaaS subscription manager that charges users recurring Lightning payments.

Requirements:
- A subscription plan selector (e.g. Basic 1000 sats/month, Pro 5000 sats/month)
- User provides a wallet connection to authorize recurring charges
- Service creates invoices on its own wallet and pays them using the user's connection
- Display subscription status: active, payment due, payment failed
- Show payment history with dates and amounts
- A cancel subscription button that stops the recurring charges
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: User selects plan → provides wallet connection → service charges on schedule → user sees payment history.`,
      },
      {
        title: "Recurring Donation Platform",
        description:
          "Build a platform where users set up recurring donations to any Lightning Address.",
        prompt: `Build a recurring donation platform that sends scheduled payments to a Lightning Address.

Requirements:
- Input field for the recipient's Lightning Address
- Input field for the donation amount in sats
- Frequency selector (e.g. every 10 seconds for demo, or daily/weekly/monthly)
- A "Start Donations" button that begins the recurring schedule
- Each interval, request an invoice from the Lightning Address and pay it
- Show a live log of each donation sent with timestamp, amount, and status
- Display a running total of sats donated
- A "Stop" button to cancel the recurring donations
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Enter Lightning Address, amount, and frequency → start → auto-pay on schedule → see live donation log.`,
      },
    ],
  },
  {
    id: "hold-invoice",
    title: "Buyer Protection Escrow",
    description:
      "Create an invoice that can be conditionally settled or cancelled — funds held until delivery is confirmed.",
    education:
      "Hold invoices enable buyer protection by accepting a payment but delaying final settlement. Funds are locked in the Lightning network until the seller confirms delivery. If something goes wrong, the hold invoice can be cancelled to refund the buyer. This creates a trustless escrow system for marketplace transactions.",
    howItWorks: [
      {
        title: "Create",
        description:
          "Seller generates a preimage and its hash. The hash is included in the hold invoice.",
      },
      {
        title: "Hold",
        description:
          "Buyer pays, but funds are locked. Only the seller has the preimage to claim them.",
      },
      {
        title: "Settle/Cancel",
        description:
          "Seller reveals preimage to receive funds after delivery, or cancels to refund the buyer.",
      },
    ],
    complexity: "advanced",
    requiredWallets: ["alice", "bob"],
    icon: "🔒",
    snippetIds: [
      "hold-invoice",
      "subscribe-hold-notifications",
      "hold-invoice-settle",
      "hold-invoice-cancel",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Coinflip Game",
        description:
          "Build a provably fair coinflip game where two players bet sats using hold invoices as escrow, and the winner gets paid.",
        prompt: `Build a provably fair coinflip game using hold invoices for escrow.

Requirements:
- Two players each provide a wallet connection
- Each player commits a bet amount (must match)
- The house creates a hold invoice for each player, and each player pays it (funds are locked, not yet settled)
- Flip a coin (use a random number or hash-based fairness scheme)
- The loser's hold invoice is settled (house collects the funds)
- The winner's hold invoice is cancelled (refunded) and the house pays the winnings to the winner's Lightning Address
- Display game state: waiting for bets, both paid, flipping, result, payout
- Show provably fair verification details
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Both players bet → hold invoices lock funds → coin flips → loser's invoice settled → winner refunded + paid winnings → result shown.`,
      },
      {
        title: "No Delivery, No Pay — Food Delivery",
        description:
          "Build a food delivery service where the customer's payment is held until delivery is confirmed, then settled or refunded.",
        prompt: `Build a food delivery app that uses hold invoices so customers only pay if their order is delivered.

Requirements:
- Customer places an order by selecting items from a menu (e.g. burger 500 sats, pizza 800 sats, drink 200 sats)
- The service creates a hold invoice for the order total
- Customer pays the hold invoice — funds are locked but not yet settled
- Display the order lifecycle with clear status steps:
  - "Order placed" → "Payment held" → "Preparing" → "Out for delivery" → "Delivered" / "Cancelled"
- A delivery driver panel with buttons to advance the order through each stage
- If the driver marks the order as "Delivered":
  - Settle the hold invoice (merchant receives the funds)
  - Show a confirmation receipt to the customer
- If the order is cancelled at any stage before delivery:
  - Cancel the hold invoice (customer is refunded)
  - Show a refund notice to the customer
- Display a timer showing how long funds have been held
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Customer orders → pays hold invoice → funds locked → driver delivers → settle invoice, or cancel → refund customer.`,
      },
      {
        title: "Lightning Liquidity Service (LSP)",
        description:
          "Build an LSP that opens a channel for a client, using a hold invoice so the client only pays if the channel is successfully opened.",
        prompt: `Build a simulated Lightning Service Provider (LSP) that uses hold invoices so clients only pay if a channel is opened.

Requirements:
- Client requests a channel by specifying a desired capacity in sats (e.g. 50,000 or 100,000 sats)
- The LSP calculates a fee (e.g. 1% of capacity) and creates a hold invoice for the fee amount
- Client pays the hold invoice — funds are locked but not yet settled
- Display the channel opening lifecycle:
  - "Fee invoice paid" → "Opening channel..." → "Channel confirmed" / "Channel failed"
- An LSP operator panel with controls to simulate:
  - "Channel Opened" — settles the hold invoice, LSP keeps the fee
  - "Channel Failed" — cancels the hold invoice, client is refunded
- Show channel details when opened: capacity, channel ID (simulated), node public key
- If the hold invoice times out before a decision, it is automatically cancelled (refund)
- Display both client and LSP perspectives side by side
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Client requests channel → pays hold invoice fee → LSP attempts to open channel → if opened, settle (LSP keeps fee) → if failed, cancel (client refunded).`,
      },
    ],
  },
  {
    id: "wrapped-invoices",
    title: "Platform Fee Collection",
    description:
      "Act as a non-custodial payment intermediary. Shopstr earns 1% on every sale by wrapping the seller's invoice with a higher amount.",
    education:
      "Wrapped invoices allow Shopstr to act as a non-custodial marketplace fee collector. By creating a hold invoice with the same payment hash as the seller's invoice (but a higher amount), the platform collects a fee for facilitating the sale. Crucially, the buyer's funds remain locked in the Lightning network - never in the platform's wallet - until settled. The platform must use its own liquidity to pay the seller's invoice first, receiving the preimage, which is then used to settle the held payment and claim the fee. This non-custodial pattern is the manual equivalent of how Lightning routing works.\n\n⚠️ Important: The platform's wrapped invoice must have a higher min_final_cltv_expiry_delta than the seller's original invoice. This ensures the platform has enough time to settle the buyer's payment after receiving the preimage from paying the seller.",
    howItWorks: [
      {
        title: "Seller Creates",
        description:
          "Seller creates a regular invoice for their product. The platform receives it and extracts the payment hash.",
      },
      {
        title: "Platform Wraps",
        description:
          "Platform creates a hold invoice with the SAME payment hash but higher amount (adding the marketplace fee).",
      },
      {
        title: "Buyer Pays",
        description:
          "Buyer pays the platform's wrapped invoice. Funds are HELD in the network (not in the platform's wallet).",
      },
      {
        title: "Platform Pays Seller",
        description:
          "Platform pays the seller's original invoice using its OWN funds. It receives the preimage.",
      },
      {
        title: "Platform Settles",
        description:
          "Platform uses the preimage to settle the buyer's held payment. The platform keeps the fee difference.",
      },
    ],
    complexity: "expert",
    requiredWallets: ["alice", "bob", "charlie"],
    icon: "🎁",
    snippetIds: [
      "make-invoice",
      "wrapped-hold-invoice",
      "subscribe-hold-notifications",
      "pay-invoice",
      "hold-invoice-settle",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Stacker News Clone",
        description:
          "Build a social news site where the platform earns revenue from zaps using wrapped invoices, while preventing sybil attacks.",
        prompt: `Build a Stacker News-style social news site that uses wrapped invoices to earn platform revenue from zaps.

Requirements:
- A feed of user-submitted posts (title, link, author)
- Users can zap (tip) posts with Lightning payments
- When a user zaps a post:
  - The post author creates an invoice for the zap amount
  - The platform wraps that invoice, adding a platform fee (e.g. 10%)
  - The zapper pays the wrapped invoice to the platform
  - The platform pays the original invoice to the author, keeping the fee & preventing sybil attacks
- Display zap counts and totals on each post
- Show a leaderboard of top-zapped posts and top earners
- Display platform revenue from fees
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: User submits post → another user zaps → platform wraps author's invoice with fee → zapper pays platform → platform pays author → platform keeps fee.`,
      },
      {
        title: "Lightning Trampoline Service",
        description:
          "Build a privacy-preserving trampoline service that hides payment recipients in exchange for a fee.",
        prompt: `Build a Lightning trampoline service that provides payment privacy by hiding the true recipient.

Requirements:
- A service where users can make payments without revealing the final destination
- The flow:
  - User provides the recipient's invoice they want to pay privately
  - The trampoline service extracts the payment hash from the invoice
  - The service creates a wrapped hold invoice with the same payment hash, adding a privacy fee (e.g. 5%)
  - User pays the trampoline's wrapped invoice
  - The trampoline pays the original recipient invoice using its own node, receiving the preimage
  - The trampoline settles the user's payment with the preimage
- Privacy benefits to explain to users:
  - The recipient only sees the trampoline node, not the payer's node
  - The payer's node only sees the trampoline, not the recipient
  - Network observers cannot link payer to recipient
- Display the payment flow visually showing the privacy barrier
- Show service stats: payments processed, total fees earned
- Include a fee calculator so users know the total cost before paying
- Handle edge cases: expired invoices, failed payments (cancel and refund)
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: User pastes recipient invoice → service wraps it with fee → user pays service → service pays recipient privately → service settles user payment → privacy preserved.`,
      },
    ],
  },
  {
    id: "decode-bolt11-invoice",
    title: "Transaction Receipt",
    description:
      "Decode an invoice to verify its properties — useful for transparent fee breakdown in marketplace transactions.",
    education:
      "A BOLT-11 invoice can be decoded into its separate fields, to access for example the invoice amount, description, payment hash, and expiry. In a marketplace context, this is useful for verifying invoice details before paying and for showing buyers a transparent breakdown of what they're paying for.",
    complexity: "medium",
    requiredWallets: [],
    icon: "🔍",
    snippetIds: ["decode-invoice"] satisfies SnippetId[],
    prompts: [
      {
        title: "Invoice Inspector Tool",
        description:
          "Build a developer tool that decodes and displays all fields of a BOLT-11 Lightning invoice.",
        prompt: `Build a Lightning invoice inspector/decoder tool.

Requirements:
- A text input where users can paste a BOLT-11 invoice string
- Decode the invoice and display all fields in a clear, labeled format:
  - Amount (in sats and millisats)
  - Description / purpose
  - Payment hash
  - Payee public key
  - Expiry time and whether it's expired
  - Creation timestamp
  - Route hints (if any)
- Add a "Copy" button for each field value
- Highlight if the invoice is expired
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Paste invoice → decode → display all fields with labels and copy buttons.`,
      },
      {
        title: "Verify Customer Payout Invoice",
        description:
          "Build a service that accepts a customer-provided invoice and verifies its amount and expiry before paying it out.",
        prompt: `Build a payout verification service that decodes and validates a customer-submitted Lightning invoice before paying it.

Requirements:
- A form where the customer pastes their BOLT-11 invoice
- The service has a preconfigured expected payout amount (e.g. set via an input or dropdown: 1000, 5000, 10000 sats)
- On submission, decode the invoice and display the parsed fields: amount, description, expiry, and payment hash
- Validate the invoice against business rules:
  - Amount must exactly match the expected payout amount — reject if it differs
  - Invoice must not be expired — reject if the expiry time has passed
  - Invoice must have enough remaining time before expiry (e.g. at least 60 seconds) — warn or reject if too close
- Show a clear pass/fail status for each validation check with green checkmarks or red crosses
- If all checks pass, show an "Approve & Pay" button that pays the invoice
- If any check fails, show an error summary explaining what went wrong and do not allow payment
- Display the result after payment (success or failure)
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Set expected payout amount → customer pastes invoice → decode → validate amount and expiry → approve and pay or reject with reason.`,
      },
    ],
  },
  {
    id: "proof-of-payment",
    title: "Order Receipt",
    description:
      "Use the payment preimage as cryptographic proof of purchase for marketplace orders.",
    education:
      "Every Lightning payment includes a preimage that serves as cryptographic proof of payment. In a marketplace, buyers can use this as a digital receipt to prove they paid for an order. This enables verifiable order history, content unlocking after purchase, and dispute resolution.",
    complexity: "medium",
    requiredWallets: [],
    icon: "✅",
    snippetIds: [
      "make-invoice",
      "pay-invoice",
      "validate-preimage",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Secret Exchange",
        description:
          "Build an atomic secret exchange where the seller encrypts data with the preimage and the buyer decrypts it after payment.",
        prompt: `Build an atomic secret exchange where paying a Lightning invoice reveals the key to decrypt a secret.

Requirements:
- The seller has secret data (e.g. an API key, download link, or password)
- The seller generates a random preimage, then encrypts the secret data using the preimage as the symmetric encryption key (e.g. AES-256)
- The seller also publishes a hash of the plaintext secret, so the buyer can verify correctness after decryption
- The seller creates an invoice from the preimage hash and shares the encrypted data + plaintext hash + invoice with the buyer
- The buyer sees the item description, price, encrypted blob, and plaintext hash — but cannot read the secret yet
- The buyer pays the invoice
- The payment preimage is atomically revealed upon successful payment
- The buyer uses the preimage to decrypt the secret data
- The buyer hashes the decrypted result and compares it to the published plaintext hash to verify they got the correct data
- Display the decryption step-by-step: preimage → decrypt → verify hash → show secret
- Note: the plaintext hash commitment makes fraud provable after the fact — the buyer can show that the decrypted data doesn't match the committed hash
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Seller encrypts secret with preimage, publishes ciphertext + plaintext hash → buyer pays → preimage revealed → buyer decrypts and verifies.`,
      },
    ],
  },
  // {
  //   id: "transaction-history",
  //   title: "Transaction History",
  //   description: "Fetch and display transaction history from a wallet.",
  //   education:
  //     "NWC allows you to query the transaction history of a wallet, useful for displaying past payments and receipts in your application.",
  //   complexity: "medium",
  //   requiredWallets: ["alice", "bob", "charlie", "david"],
  //   icon: "📜",
  // },
  /*{
    id: "nostr-zap",
    title: "Nostr Zap",
    description: "Send a zap (payment) to a Nostr user or content.",
    education:
      "Zaps are Lightning payments sent through Nostr, typically used to tip content creators. They combine Lightning payments with Nostr social features.",
    complexity: "advanced",
    requiredWallets: ["alice", "bob"],
    icon: "⚡",
  },*/
  {
    id: "payment-forwarding",
    title: "Affiliate Commission",
    description:
      "Listen to incoming payments and auto-forward a percentage to a referrer's Lightning Address.",
    education:
      "Payment forwarding enables affiliate commission models on Shopstr. When a buyer completes a purchase through an affiliate link, the platform can automatically forward a percentage of the sale to the affiliate's Lightning Address. This creates transparent, instant commission payouts without intermediaries.",
    howItWorks: [
      {
        title: "Configure",
        description:
          "Platform sets up forwarding to the affiliate's Lightning Address with a percentage.",
      },
      {
        title: "Receive",
        description:
          "Buyer pays the platform. The platform's wallet receives the payment notification.",
      },
      {
        title: "Forward",
        description:
          "Platform automatically forwards the configured percentage to the affiliate.",
      },
    ],
    complexity: "medium",
    requiredWallets: ["alice", "bob", "charlie"],
    icon: "🔀",
    snippetIds: [
      "subscribe-notifications",
      "request-invoice-from-address",
      "pay-lightning-address",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Income Splitter",
        description:
          "Build a service that receives payments and automatically forwards a percentage to another Lightning Address.",
        prompt: `Build an income splitter service that forwards a percentage of incoming payments.

Requirements:
- Configuration panel to set:
  - Forwarding recipient (Lightning Address)
  - Forwarding percentage (e.g. 80%)
  - Reserve percentage for routing fees (e.g. 1%)
- Subscribe to incoming payment notifications
- When a payment is received:
  - Calculate the forwarding amount based on the configured percentage
  - Request an invoice from the recipient's Lightning Address and pay it
- Display a live log of received payments and forwarded amounts
- Show a running summary: total received, total forwarded, total retained
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Configure split → receive payment → calculate forward amount → pay to Lightning Address → log result.`,
      },
    ],
  },
  {
    id: "payment-prisms",
    title: "Multi-Party Split",
    description:
      "Split incoming payments across multiple parties — manufacturer, platform, and affiliate all get paid instantly.",
    education:
      "Payment Prisms on Shopstr allow a single marketplace purchase to fund multiple recipients. When a buyer pays for a product, the platform can split the payment between the manufacturer, itself (platform fee), and the affiliate (referral commission). Prisms can also be recursive. Reserve 1% for routing fees on each payment.",
    howItWorks: [
      {
        title: "Configure",
        description:
          "Platform sets up a prism split with percentages for seller and affiliate.",
      },
      {
        title: "Receive",
        description:
          "Buyer pays the platform. The platform's wallet receives the payment notification.",
      },
      {
        title: "Split",
        description:
          "Platform automatically splits the payment, forwarding to seller and affiliate.",
      },
    ],
    complexity: "advanced",
    requiredWallets: ["alice", "bob", "charlie", "david"],
    icon: "🔺",
    snippetIds: [
      "subscribe-notifications",
      "request-invoice-from-address",
      "pay-lightning-address",
      "pay-invoice",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Band Revenue Splitter",
        description:
          "Build a payment page for a band that automatically splits incoming payments among all members.",
        prompt: `Build a band revenue splitter that distributes incoming payments to multiple members.

Requirements:
- Configuration panel to set up band members:
  - Each member has a name, Lightning Address, and split percentage
  - Support 2-5 members
  - Percentages must total 100% (minus a reserve for routing fees)
- A payment page that shows the band name and a QR code / Lightning Address for receiving payments
- Subscribe to incoming payment notifications
- When a payment is received:
  - Calculate each member's share based on their percentage
  - Request invoices from each member's Lightning Address and pay them
- Display a live split log showing each distribution
- Show per-member totals and an overall summary
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Configure members & splits → receive payment → calculate shares → pay each member → log distributions.`,
      },
    ],
  },
  {
    id: "fiat-conversion",
    title: "Multi-Currency Pricing",
    description:
      "Convert between sats and fiat currencies — sellers price in USD, buyers pay in sats.",
    education:
      "Marketplaces need to display Bitcoin amounts in familiar fiat currencies. Sellers can price products in USD, EUR, or any fiat currency while buyers pay in sats. Learn how to fetch exchange rates and convert amounts for transparent marketplace pricing.",
    complexity: "simple",
    requiredWallets: [],
    icon: "💱",
    snippetIds: [
      "get-fiat-currencies",
      "sats-to-fiat",
      "fiat-to-sats",
      "get-btc-rate",
    ] satisfies SnippetId[],
    prompts: [
      {
        title: "Bitcoin Price Converter",
        description:
          "Build a real-time converter tool between sats and multiple fiat currencies.",
        prompt: `Build a Bitcoin/sats to fiat currency converter.

Requirements:
- Input field for an amount in sats
- Dropdown to select fiat currency (USD, EUR, GBP, JPY, etc.)
- Display the converted fiat amount in real time as the user types
- Also support reverse conversion: input fiat amount, show equivalent in sats
- Show the current exchange rate (sats per dollar, etc.)
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Enter amount → select currency → see converted value in real time.`,
      },
    ],
  },
  // Nostr section
  {
    id: "zapvertising",
    title: "Zapvertising",
    description:
      "Boost product listings by zapping sats. Merchants pay for visibility via Lightning — the zap IS the ad.",
    education:
      "Zapvertising uses NIP-57 Lightning Zaps to create a permissionless advertising model. A merchant zaps their own listing (or the platform zaps on their behalf) to boost its visibility. The zap creates a kind-9735 receipt on Nostr relays, which ranking algorithms use to surface boosted content. Unlike traditional ads, there's no ad network — direct Lightning payment, instant settlement, pseudonymous.",
    complexity: "advanced",
    section: "nostr",
    requiredWallets: ["alice", "bob", "charlie"],
    icon: "📢",
    snippetIds: [
      "make-invoice",
      "pay-invoice",
      "subscribe-notifications",
    ] satisfies SnippetId[],
    howItWorks: [
      {
        title: "List",
        description: "Merchant creates a product listing on Shopstr.",
      },
      {
        title: "Boost",
        description:
          "Merchant sets a boost budget. Platform creates a zap request (kind 9734) to the listing.",
      },
      {
        title: "Pay",
        description:
          "The zap is paid via Lightning. A kind-9735 receipt is published to relays.",
      },
      {
        title: "Rank",
        description:
          "Boosted listings appear higher in search results and feeds.",
      },
    ],
    prompts: [
      {
        title: "Zapvertising Marketplace",
        description:
          "Build a marketplace where merchants boost listings with zaps and boosted items rank higher.",
        prompt: `Build a Zapvertising-powered marketplace where merchants boost their listings with Lightning zaps.

Requirements:
- A product listing feed with items showing title, price, and zap count
- Merchants can select a listing and set a boost budget in sats
- The boost creates a NIP-57 zap request (kind 9734) to the listing's author
- Pay the zap invoice via Lightning to complete the boost
- Publish a zap receipt (kind 9735) to Nostr relays
- Boosted listings display a "⚡ Boosted" badge
- Rankings sort boosted items to the top of the feed
- Show the NIP-57 flow visually: LNURL resolution → zap request → invoice → payment → receipt
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Merchant selects listing → sets boost budget → platform creates zap request → pays via Lightning → receipt published → listing ranks higher.`,      },
    ],
  },
  {
    id: "frostr",
    title: "FROSTR Team Signing",
    description:
      "Threshold multi-sig for Nostr teams. Split your nsec into shares — no single point of key compromise.",
    education:
      "FROSTR (FROst over NostR) uses FROST threshold signatures to split a Nostr private key into k-of-n shares. A 2-of-3 setup means any 2 holders can sign, but 1 alone cannot. Shares can be instantly revoked and rotated without changing the public key (npub). Perfect for marketplace teams where multiple people need to manage a shop without sharing the full key.",
    complexity: "expert",
    section: "nostr",
    requiredWallets: ["alice", "bob", "charlie"],
    icon: "🔐",
    snippetIds: ["make-invoice"] satisfies SnippetId[],
    howItWorks: [
      {
        title: "Create",
        description:
          "Admin generates a 2-of-3 FROSTR keyset. The npub is the shop identity.",
      },
      {
        title: "Distribute",
        description:
          "Three shares created: Admin keeps one, gives one each to Team Member A and B.",
      },
      {
        title: "Sign",
        description:
          "When a signature is needed, any 2 of 3 share holders coordinate to produce it.",
      },
      {
        title: "Revoke",
        description:
          "If Member B leaves, Admin revokes their share. Signing still works with remaining 2.",
      },
    ],
    prompts: [
      {
        title: "Multi-Sig Shop Management",
        description:
          "Build a shop management dashboard where a team shares signing authority with FROSTR.",
        prompt: `Build a team management interface using FROSTR threshold signatures.

Requirements:
- A dashboard showing the current keyset (threshold, total shares, group ID)
- Share holder list with status indicators (active/revoked)
- Button to create a new 2-of-3 FROSTR keyset
- Visual flow showing share distribution to team members
- Sign request panel: initiate a signing request for a Nostr event
- Each share holder can contribute a partial signature
- When threshold is met, show the combined signature being produced
- Revocation panel: admin can revoke a team member's share
- After revocation, show that remaining active shares can still sign
- Display the final BIP-340 Schnorr signature — indistinguishable from single-sig
- Use React and TypeScript
- Write tests using vitest and playwright. Take screenshots and review the screenshots.

The flow: Create keyset → distribute shares → sign request → partial sigs → combined signature → revoke share → still signable with remaining shares.`,      },
    ],
  },
  // Bitcoin Connect items
  {
    id: "bitcoin-connect-button",
    title: "Button",
    description:
      "Add a single button component to let marketplace users connect their Lightning wallet",
    education:
      "The Bitcoin Connect Button is the simplest way to add Lightning wallet connectivity to your marketplace. Just drop in the <Button /> component and it handles everything: showing a connect button, opening the wallet selection modal, and displaying the connected wallet's balance. Perfect for letting buyers and sellers connect their wallets on Shopstr.",
    icon: "⚡",
    section: "bitcoin-connect",
    complexity: "simplest",
    requiredWallets: ["alice", "bob"],
    snippetIds: ["bc-init", "bc-button"],
  },
  {
    id: "connect-wallet",
    title: "Connect Modal",
    description:
      "Programmatically launch a modal to let marketplace users connect their Lightning wallet",
    education:
      "Bitcoin Connect provides a universal wallet connection modal that supports multiple wallet types including NWC, browser extensions, and mobile apps. It abstracts away the complexity of wallet integration, making it easy to add Lightning payments to any marketplace application on Shopstr.",
    icon: "🔗",
    section: "bitcoin-connect",
    complexity: "simple",
    requiredWallets: ["alice", "bob"],
    snippetIds: ["bc-init", "bc-launch-modal", "bc-disconnect"],
  },
  {
    id: "pay-button",
    title: "Pay Button",
    description:
      "A button component that launches the payment modal for marketplace checkout flows",
    education:
      "The PayButton component provides a one-click payment experience for marketplace checkout. Pass an invoice and it handles everything: showing the payment modal with QR code, connecting wallet if needed, and completing the payment. Perfect for product checkout and instant purchases on Shopstr.",
    icon: "💸",
    section: "bitcoin-connect",
    complexity: "medium",
    requiredWallets: ["alice", "bob"],
    snippetIds: ["bc-init", "bc-pay-button"],
  },
  {
    id: "payment-modal",
    title: "Payment Modal",
    description: "Programmatically launch a modal to process marketplace payments",
    education:
      "The launchPaymentModal function gives you programmatic control over the marketplace payment flow. It returns a setPaid function for marking external payments (like QR code scans), and fires callbacks when payment completes or is cancelled. Ideal for custom checkout flows and dynamic invoice generation on Shopstr.",
    icon: "🪟",
    section: "bitcoin-connect",
    complexity: "medium",
    requiredWallets: ["alice", "bob"],
    snippetIds: ["bc-init", "bc-launch-payment-modal"],
  },
];

const getComplexityIndex = (complexity: ScenarioComplexity) => {
  switch (complexity) {
    case "simplest":
      return 0;
    case "simple":
      return 1;
    case "medium":
      return 2;
    case "advanced":
      return 3;
    case "expert":
      return 4;
  }
};

const getSectionIndex = (section?: ScenarioSection) => {
  if (!section || section === "scenarios") return 0;
  if (section === "nostr") return 1;
  if (section === "bitcoin-connect") return 2;
  return 3;
};

export const scenarios = unorderedScenarios.sort((a, b) => {
  // First sort by section
  const sectionDiff = getSectionIndex(a.section) - getSectionIndex(b.section);
  if (sectionDiff !== 0) return sectionDiff;
  // Then sort by complexity within each section
  return getComplexityIndex(a.complexity) - getComplexityIndex(b.complexity);
});

export function getScenarioById(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id);
}
